qlik-oss/sn-scatter-plot

- src/models/extremum-model/__tests__/delta.spec.js
- src/models/extremum-model/__tests__/index.spec.js
> refactor: `extremum model` unit tests

- Dockerfile
- docker-compose.yml
- examples/plugins/plugin_axes.html
- examples/plugins/plugin_line.html
- examples/plugins/plugin_point.html
- test/rendering/index.spec.js
- Fix problem with Windows
- Also, fix issue with browser
> fix: local rendering tests on Windows

- src/locale/all.json
Fix density string translation outside sense client
> fix: density string translation

- src/__tests__/logical-size.spec.js
- src/__tests__/snapshot.spec.js
- src/ext/__tests__/property-definition.spec.js
- src/hooks/__tests__/use-core.spec.js
- src/hooks/__tests__/use-models.spec.js
- src/hooks/__tests__/use-render.spec.js
- src/hooks/__tests__/use-settings.spec.js
- src/hooks/__tests__/use-view-state.spec.js
- src/hooks/__tests__/view-state.spec.js
- src/hooks/use-actions/__tests__/index.spec.js
- src/hooks/use-actions/__tests__/use-lasso.spec.js
- src/hooks/use-actions/__tests__/use-select.spec.js
- src/locale/__tests__/index.spec.js
- src/models/chart-model/__tests__/index.spec.js
- src/models/disclaimer-model/resolve/__tests__/disclaimers.spec.js
- src/models/extremum-model/__tests__/index.spec.js
- src/picasso-components/point-label/__tests__/index.spec.js
- src/picasso-components/react-components/__tests__/react-renderer.spec.js
Add missing unit tests, especially for hooks.
> fix: unit tests

- src/picasso-definition/components/index.js
- src/picasso-definition/components/out-of-bounds/__tests__/index.spec.js
- src/picasso-definition/components/out-of-bounds/index.js
To fix https://github.com/qlik-oss/sn-scatter-plot/issues/128.
> fix: fix oob

- src/picasso-definition/components/heat-map-legend/__test__/index.spec.js
- src/picasso-definition/components/heat-map-legend/index.js
Fix https://github.com/qlik-oss/sn-scatter-plot/issues/147
> fix: bin legend label style

- src/custom-tooltip/__tests__/utils.spec.js
- src/custom-tooltip/chart/__tests__/container.spec.js
- src/custom-tooltip/chart/__tests__/index.spec.js
- src/custom-tooltip/chart/__tests__/object.spec.js
- src/custom-tooltip/chart/__tests__/properties.spec.js
- src/custom-tooltip/chart/__tests__/session-states.spec.js
- src/custom-tooltip/chart/container.js
- src/custom-tooltip/chart/index.js
- src/custom-tooltip/chart/object.js
- src/custom-tooltip/chart/properties.js
- src/custom-tooltip/chart/session-states.js
- src/custom-tooltip/constants/index.js
- src/custom-tooltip/migrators/__tests__/attr-expr-migrator.spec.js
- src/custom-tooltip/migrators/attr-expr-migrator.js
- src/custom-tooltip/migrators/index.js
- src/custom-tooltip/model/index.js
- src/custom-tooltip/picasso-definitions/__tests__/attr-expr.spec.js
- src/custom-tooltip/picasso-definitions/__tests__/attribute.spec.js
- src/custom-tooltip/picasso-definitions/__tests__/images.spec.js
- src/custom-tooltip/picasso-definitions/__tests__/nodes.spec.js
- src/custom-tooltip/picasso-definitions/attr-expr.js
- src/custom-tooltip/picasso-definitions/attribute.js
- src/custom-tooltip/picasso-definitions/nodes.js
- src/custom-tooltip/promises/images.js
- src/custom-tooltip/promises/index.js
- src/custom-tooltip/service/__tests__/index.spec.js
- src/custom-tooltip/service/index.js
- src/custom-tooltip/utils.js
This code will be removed once the module has been refactored and moved into qlik-chart-modules.
> refactor: add custom-tooltip-module

- src/ext/property-definition/__tests__/index.spec.js
- src/ext/property-definition/compression-note-properties.js
- src/ext/property-definition/index.js
> fix: add notes for compression mode

- src/picasso-definition/components/mini-chart/__tests__/index.spec.js
- src/picasso-definition/components/mini-chart/index.js
- src/picasso-definition/components/navigation-panel/__tests__/index.spec.js
- src/picasso-definition/components/navigation-panel/index.js
fix https://github.com/qlik-oss/sn-scatter-plot/issues/177 and https://github.com/qlik-oss/sn-scatter-plot/issues/176
> fix: hide nav and minchart in snapshot

- src/picasso-components/ref-line-labels/internal/label-helper.js
- src/picasso-definition/components/reference-lines/__tests__/index.spec.js
- src/picasso-definition/components/reference-lines/__tests__/labels.spec.js
- src/picasso-definition/components/reference-lines/__tests__/lines.spec.js
- src/picasso-definition/components/reference-lines/index.js
- src/picasso-definition/components/reference-lines/labels.js
- src/picasso-definition/components/reference-lines/lines.js
> fix: fix ref-line and ref-line-labels color and visibility

- src/data-handler/index.js
- src/data-handler/is-binned-data.js
> fix: fix snapshot in case qInitialDataFetch is set

- src/data-handler/index.js
- src/hooks/__tests__/use-core.spec.js
- src/hooks/use-actions/__tests__/index.spec.js
- src/hooks/use-actions/index.js
- src/hooks/use-core.js
- src/hooks/use-models.js
- src/index.js
- src/models/disclaimer-model/index.js
- src/models/disclaimer-model/resolve/__tests__/disclaimers.spec.js
- src/models/disclaimer-model/resolve/disclaimers.js
- src/models/disclaimer-model/resolve/index.js
- src/picasso-definition/components/__tests__/index.spec.js
- src/picasso-definition/components/axes/index.js
- src/picasso-definition/components/heat-map-highlight/__tests__/index.spec.js
- src/picasso-definition/components/heat-map-highlight/index.js
- src/picasso-definition/components/index.js
- src/picasso-definition/components/mini-chart/__tests__/index.spec.js
- src/picasso-definition/components/mini-chart/index.js
- src/picasso-definition/index.js
Remove panzoom and data_binning feature flag.
> refactor: remove panzoom and data_binning flags

- src/services/color-service/legend/__tests__/settings.spec.js
- src/services/color-service/legend/settings.js
fix https://github.com/qlik-oss/sn-scatter-plot/issues/132
> fix: truncated categorical legend

- .circleci/api-gov.sh
- .circleci/config.yml
Hello!
We are migrating to a new image for doing API compliance.  
Check that the paths and names are correct to your repo.If you have any questions don't hesitate to reach out.
> chore: update api compliance

- src/interactive/range/index.js
- src/interactive/range/range-tap.js
> feat: edit range select bubbles

- src/models/extremum-model/get-bin-extremum.js
- src/models/extremum-model/index.js
> fix: update max min when all data points in bin have the same value

- src/picasso-definition/components/navigation-panel/__tests__/index.spec.js
- src/picasso-definition/components/navigation-panel/index.js
https://github.com/qlik-oss/sn-scatter-plot/issues/221
> fix: navigation panel console error in snapshot

- src/picasso-components/react-components/disclaimer.jsx
> fix: fix disclaimer size and position

- package.json
- src/constants/__tests__/keys.spec.js
- src/constants/keys.js
- src/services/tooltip-service/__tests__/index.spec.js
- src/services/tooltip-service/index.js
- src/services/tooltip-service/section/__tests__/trendline.spec.js
- src/services/tooltip-service/section/index.js
- src/services/tooltip-service/section/trendline.js
- src/services/trendlines-service/__tests__/index.spec.js
- src/services/trendlines-service/index.js
- yarn.lock
> fix: missing trendlines tooltip

- src/picasso-components/heat-map-highlight/__tests__/extract-image-data.spec.js
- src/picasso-components/heat-map-highlight/extract-image-data.js
- src/picasso-components/heat-map-highlight/index.js
- src/picasso-definition/components/heat-map-highlight/__tests__/index.spec.js
- src/picasso-definition/components/heat-map-highlight/index.js
- src/picasso-definition/components/index.js
Fix when is rtl, bin range selection highlight area is not correct.
After fix
https://user-images.githubusercontent.com/25456307/152139699-abe72d60-086a-49bc-b28b-3363619abb86.mov
> fix: bin range selection highlight layer with rtl

- src/picasso-definition/brush/__tests__/point-brush.spec.js
- src/picasso-definition/brush/point-brush.js
fix https://github.com/qlik-oss/sn-scatter-plot/issues/202
Need picasso changes https://github.com/qlik-oss/picasso.js/pull/678
Before fixing:
https://user-images.githubusercontent.com/25456307/152969764-5134fd6c-0486-4d2d-ab37-a4f3def8d16a.mov
After fixing:
https://user-images.githubusercontent.com/25456307/152969840-2eedb978-dce6-4e98-82e5-9a0e8f8e0234.mov
> fix: points selection highlight hidden issue

- src/services/trendlines-service/index.js
> fix: animation of trendlines that failed to calculate

- src/constants/modes.js
Fix x axis mode, so in small size chart, x axis is still showing and disappear same as y axis.
> fix: x axis mode

- src/models/tick-model/__tests__/index.spec.js
Add unit tests for:
- https://github.com/qlik-oss/sn-scatter-plot/pull/272
> fix: unit tests for the case formatter has no pattern function

- src/ext/property-definition/__tests__/index.spec.js
- src/ext/property-definition/index.js
- src/locale/all.json
https://user-images.githubusercontent.com/25456307/168034364-2326bc9d-864b-49a0-a696-4ed89b649921.mov
> feat: add property in axis simple mode

- test/integration/__fixtures__/scatter_render_zoom.fix.js
- test/integration/index.spec.js
Added a new test for Zoom data in the scatterplot.
1. Check if data point is seen and that out-of-bounce point is not seen
2.  Zoom in 5 times through navigation button
3. Check if data point is not seen and that out-of-bounce point is seen
4. reset zoom through navigation house button
5. Check if data point is seen and that out-of-bounce point is not seen
> test: added zoom test

- .circleci/config.yml
- README.md
- docs/development.md
- Allow publishing from release branch to npm
- Add documentation about releasing and patching
> fix: allow publishing from release branch

- src/custom-tooltip/promises/images.js
This PR fixes the broken image in the mashups due to missing config in nebula's session
https://jira.qlikdev.com/browse/QB-14431
> fix(custom-tooltip): fix broken image in mashups

- package.json
- src/ext/property-definition/styling-definitions/styling-panel-definition.js
- yarn.lock
providing feature flag to font resolver in qlik-chart-modules
> fix: providing feature flag to font resolver in qlik-chart-modules

- src/models/tick-model/ticks/__tests__/tick-helper.spec.js
- src/models/tick-model/ticks/tick-helper.js
To fix https://jira.qlikdev.com/browse/QB-21908
> fix: fix duplicated tick value labels

- src/picasso-components/react-components/react-renderer.js
To fix https://jira.qlikdev.com/browse/QB-26098
> fix: fix using old root after root is unmounted
