src/hooks/use-core.js

Kudos to @tasseKATT , who discovered the root cause.
SVG renderer generates new DOMs, which are not recycled well on Safari, causing the crash.
The fix is to change it to `canvas`
Manually on iPhone 12 connected to Mac. The issue is resolved.

fix: crashing on iPhone

---

nebula.config.js
src/models/chart-model/__tests__/index.spec.js
src/models/chart-model/index.js

We can postpone fetching data during panning. This will increase performance and prevent legend from switching back and forth between binned and normal data. It also avoids showing two types of data simultaneously on the chart (see video 1).
Current: 
https://user-images.githubusercontent.com/70384379/142886214-d5c8be1b-68c1-4aba-85ad-7a8ead1c16d2.mov
After fix:
https://user-images.githubusercontent.com/70384379/142886264-3b6ec532-db6a-4e72-9ca5-e39f91528ef8.mov

fix: avoid fetching data if panning is in progress

---

src/picasso-components/point-label/index.js

To fix https://github.com/qlik-oss/sn-scatter-plot/issues/125.
The bubbles rendered later will be on top of the bubbles rendered before.
So the label should based on this order.

fix: fix label order

---

src/picasso-definition/components/heat-map/__tests__/index.spec.js
src/picasso-definition/components/heat-map/index.js

Remove adding 0.5 to the width and height of a bin. 
With 0.5, it can remove the white gaps between each bins, but will causing sometime labels not showing(not enough space) or bins range selection has weird colors. So will remove adding 0.5.
Fixing:

fix: label and range highlighting issue

---

.circleci/config.yml

chore: fix api compliance

---

src/picasso-definition/interactions/__tests__/pan.spec.js
src/picasso-definition/interactions/__tests__/pinch.spec.js
src/picasso-definition/interactions/native.js
src/picasso-definition/interactions/pan.js
src/picasso-definition/interactions/pinch.js
src/utils/__tests__/event-utils.spec.js
src/utils/event-utils.js
src/view-handler/__tests__/zoom.spec.js
src/view-handler/zoom.js

fix https://github.com/qlik-oss/sn-scatter-plot/issues/152 and https://github.com/qlik-oss/sn-scatter-plot/issues/153
1. Fix when sometimes areaPanend is called and this[eventName] is undefined even when pan start is not called. 
2. Fix when transition between bin and normal, component width and height is 0, causing calculated xAxisMin etc is NaN. The fix is to store width and height and use them if the component width and height is 0.

fix: pinch issue between bin and normal

---

src/picasso-definition/components/__tests__/index.spec.js
src/picasso-definition/components/index.js

Fix bin data range selection highlight layer under min chart and navigation panel.
Before fix:
After fix:

fix: bin range selection highlight layer order

---

src/interactive/lasso/event.js
src/interactive/range/event.js
src/interactive/tap/event.js
src/picasso-components/heat-map-highlight/index.js
src/picasso-definition/interactions/__tests__/native.spec.js
src/picasso-definition/interactions/__tests__/pan.spec.js
src/picasso-definition/interactions/__tests__/pinch.spec.js
src/picasso-definition/interactions/native.js
src/picasso-definition/interactions/pan.js
src/picasso-definition/interactions/pinch.js
src/utils/__tests__/is-in-bin-range-selection.spec.js
src/utils/__tests__/is-in-bin-value-selection.spec.js
src/utils/is-in-bin-value-selection.js

Fix when first doing selections with tap or lasso, and then doing bin range selection, the range selection base image is not correct.
The fix is when start doing selection and the image is undefined, we store the image.
Disable pan zoom and pinch when is in bin value selection as the old scatter plot. So can avoid doing value selection and move the chat, then do range selection, the base image is not correct.
See the issue here:
https://user-images.githubusercontent.com/25456307/151179099-f636ca32-ecbf-45f0-8f4e-cb53e945ffc9.mov
After fix:
https://user-images.githubusercontent.com/25456307/151323351-64743759-91d8-4061-853d-d1892a8e81b3.mov

fix: bin range highlight issue

---

src/picasso-definition/components/heat-map/index.js

There is a scenario where all data points in a bin has the same x and/or y values. This can cause bin width/height less than 1 px and the bins are almost invisible.

fix: set min bin width/height to 1 px

---

src/picasso-definition/components/navigation-panel/__tests__/index.spec.js
src/view-handler/__tests__/index.spec.js
src/view-handler/index.js
src/view-handler/zoom.js

To fix: https://github.com/qlik-oss/sn-scatter-plot/issues/220
The issue happens because scale is not updated after pressing home button (thanks to @jjxie for pointing out the root cause). This can be fixed by updating the scale everytime you setDataView.

fix: update scale when update dataview

---

src/picasso-definition/components/reference-lines/__tests__/labels.spec.js
src/picasso-definition/components/reference-lines/labels.js

For performance reason (avoiding possible crash on mobile phone due to svg nodes overloading browsers).

fix: change svg to canvas for renderer of reference line labels

---

src/services/selection-service/__tests__/index.spec.js
src/services/selection-service/index.js

Fix the issue when having bin range selection and then clear selection, the highlight img is still there.
Before fixing:
https://user-images.githubusercontent.com/25456307/152179629-cc18c4ce-280c-41da-9e44-5e0461b979a9.mov
After fixing:
https://user-images.githubusercontent.com/25456307/152179525-a64e10d3-5b76-461b-8eaa-c671c4003453.mov

fix: clear bin highlight img when clear selection

---

src/interactive/lasso/event.js
src/interactive/range/event.js
src/interactive/tap/event.js
src/picasso-components/heat-map-highlight/index.js

Fix the issue when doing bin range selection, sometimes the color is not correct. This is due to how canvas deals with color with opacity. 
`Due to the lossy nature of converting to and from premultiplied alpha color values, pixels that have just been set using putImageData() might be returned to an equivalent getImageData() as different values. `
The issue is like this, in some sizes unexpected colors (light blue) will show up.
The fix now changes the canvas opacity to 1 before get image, so all the colors are solid color. 
But in one scenarios, tap on chart to get into selection mode, then pan/zoom the chart. Since the dataview changes, we will render the highlight component and also need to get a new image, this image is with inactive style (opacity: 0.3, not added to canvas directly). …

fix: bin range highlight color issue

---

src/constants/__tests__/numbers.spec.js
src/constants/numbers.js
src/picasso-definition/components/__tests__/index.spec.js
src/picasso-definition/components/heat-map-labels/__test__/index.spec.js
src/picasso-definition/components/heat-map-labels/index.js
src/picasso-definition/components/heat-map/__tests__/index.spec.js
src/picasso-definition/components/heat-map/index.js
src/picasso-definition/components/index.js
src/picasso-definition/components/point-labels/__test__/index.spec.js
src/picasso-definition/components/point-labels/index.js
src/picasso-definition/components/point/__tests__/index.spec.js
src/picasso-definition/components/point/index.js
src/view-handler/index.js

It is unnecessary to do transformation when the number of points or bins is lower than a threshold. I set it at 100, based on the below tests.
Based on the below tests, at 118 bins (+118 labels) the rendering time is roughly the same. Only above 118 bins that we need transformation.
For Iphone 12, 50 seems be be a better threshold. However, since the rendering times are much lower than on Macbook, it also makes sense to set the threshold at 100.
Sanity check: console log when transformation happens.
- Threshold set at 118 (should transform)
https://user-images.githubusercontent.com/70384379/152244400-cdb01071-f8f1-4e94-bea3-9c606b22e5da.mov
- Threshold set at 119 (should not transform)
https://user-images.githubusercontent.com/70384379/152245188-1308427e-4754-4fd5-a06f-3a8e961572df.mov
- …

fix: set lower limit for transformation

---

src/models/tick-model/ticks/__tests__/index.spec.js
src/models/tick-model/ticks/__tests__/tick-helper.spec.js
src/models/tick-model/ticks/index.js
src/models/tick-model/ticks/tick-helper.js

Fix: https://github.com/qlik-oss/sn-scatter-plot/issues/191, https://github.com/qlik-oss/sn-scatter-plot/issues/179, and https://github.com/qlik-oss/sn-scatter-plot/issues/127
- https://github.com/qlik-oss/sn-scatter-plot/issues/191: fixed by making sure zero always shown if it is within the range.
- Y-direction
https://user-images.githubusercontent.com/70384379/152697358-8d659f9d-e202-4a93-a5fa-bf778fd07ca4.mov
- X-direction
https://user-images.githubusercontent.com/70384379/152697585-65acaa2c-76e4-4866-92c5-c8368e41db6f.mov
- https://github.com/qlik-oss/sn-scatter-plot/issues/127: fixed by making sure there are always at least two ticks shown when zooming (preferably 3).
https://user-images.githubusercontent.com/70384379/152697929-e0a6ef14-35b3-4351-bb63-062c6900032a.mov

fix: improve grid lines

---

src/models/tick-model/ticks/__tests__/tick-helper.spec.js
src/models/tick-model/ticks/tick-helper.js

After comparing with the old chart, I realized that the lower limit of 75% of the nominal grid size is a bit too tight.

fix: grid lines adjust lower limit

---

src/hooks/view-state.js
src/models/chart-model/__tests__/format-pattern-from-range.spec.js
src/models/chart-model/__tests__/index.spec.js
src/models/chart-model/format-pattern-from-range.js
src/models/chart-model/index.js
src/models/tick-model/__tests__/index.spec.js
src/models/tick-model/index.js

- Fix: #248 
- Root cause: default autoFormat formatter of Picasso only generates a maximum of 2 decimal digits, which is not enough when the range is very narrow.
- The fix: create a format pattern from range, allowing as many decimal digits as necessary. Assign this pattern for formatters of X-axis and Y-axis.
- Files changed:
- [src/hooks/view-state.js](https://github.com/qlik-oss/sn-scatter-plot/pull/254/files#diff-0bbff74d9a79fd8c4daab7f9a562ef14b05866ae75e72aefbf9037bc3821c8ef): in the new code, in tick model, we get the formatters directly from chart. Therefore, there's no need to update tick-model formatters.
- [src/models/chart-model/format-pattern-from-range.js](https://github.com/qlik-oss/sn-scatter-plot/pull/254/files#diff-f2d4aa39fecd085b9c2872e38df1356bb1eaf4d23004871a940a647 …

fix: tick model generate decent granularity

---

src/picasso-components/heat-map-highlight/index.js

To fix: #258 
The fix: use drawImage, with is more performant than putImageData
Verification: no more crash
https://user-images.githubusercontent.com/70384379/154118916-0b54cd87-4649-4fc6-a543-d36b9508110b.mov

fix: highlight layer performance improvement

---

src/models/extremum-model/index.js

To fix #263 by adjusting the max/min in case max = min and all data points in bins have the same value against an axis.

fix: update max min when all data points in bin have the same value

---

src/models/tick-model/index.js

To fix https://jira.qlikdev.com/browse/QB-9507 caused by https://github.com/qlik-oss/sn-scatter-plot/pull/254

fix: add sanity check for formatter without pattern

---

src/picasso-components/ref-line-labels/internal/__tests__/label-helper.spec.js

Add unit tests for:
- https://github.com/qlik-oss/sn-scatter-plot/pull/271

fix: ref-line-label hasEngineFormat should handle when valueLabel is not a string (unit tests)

---

src/ext/property-definition/__tests__/index.spec.js
src/ext/property-definition/index.js

For auto chart to show inner object properties in simple mode, we have to pass in inner object properties to properties panel. So replace the places where using args.properties(auto chart properties) to props(data)
https://user-images.githubusercontent.com/25456307/172373636-0105c8c1-ee2f-4317-bb7a-2a2615b765c5.mov

refactor: use data instead of args properties

---

src/ext/property-definition/index.js

To support this PR: https://github.com/qlik-trial/analytics/pull/228

fix(analytic-creation): default label for resetting in simple edit mode

---

src/picasso-definition/components/navigation-panel/__tests__/index.spec.js
src/picasso-definition/components/navigation-panel/index.js

Fix for [QB-10212](https://jira.qlikdev.com/browse/QB-10212).
If `navigation` was missing in layout, `show` would be set to `undefined`, which is the same as not defining a show function at all, and then it defaults to `true`.

fix: correct navigation panel show value

---

src/hooks/__tests__/use-settings.spec.js
src/hooks/use-settings.js
src/models/chart-model/__tests__/index.spec.js
src/models/chart-model/index.js

As @tasseKATT pointed out, splitting size and constraints useEffect hooks (https://github.com/qlik-oss/sn-scatter-plot/pull/261) causes unnecessary renderings and problem with elongated points.
Since animations don't give users added value when resizing, animations can be disable as well when resizing.
What's more, Niclas and I realised that we don't need to monitor `constraints` in the `useEffect` hook of the useSettings, since when constraints change, we don't need to update `dockService`, `colorService` or `settings`.
I have tested going in and out of `Edit Sheet`, lasso selection, and tooltip in `Play Story` of Storytelling to verify that the constraints are still working properly after the fix.

fix: remove constraints from useEffect of useSettings

---

src/custom-tooltip/utils.js
src/interactive/tap/event.js

The x and y coordinates in `event.center` from HammerJS events are rounded up and can therefore differ from the x and y coordinates from the native mousemove `event` which is rounded down.
Changing to use `event.srcEvent` instead of event.center and rounding the value down when the event comes from HammerJS.
This is to get same results from `chart.shapesAt` look-ups based on coordinates from for example tap selections (HammerJS event) and tooltip hover (native mousemove event).

refactor: use event.srcEvent instead of event.center to calculate tap position

---

src/models/chart-model/__tests__/format-pattern-from-range.spec.js
src/models/chart-model/__tests__/index.spec.js
src/models/chart-model/format-pattern-from-range.js
src/models/chart-model/index.js
src/models/tick-model/__tests__/index.spec.js
src/models/tick-model/index.js

Cherry pick from this PR by Quan: https://github.com/qlik-oss/sn-scatter-plot/pull/350
To patch this bug: https://jira.qlikdev.com/browse/QB-16713
File changes are identical to https://github.com/qlik-oss/sn-scatter-plot/pull/350, except for the png file, which did not exist in v3.19.3

fix: axis tick value labels in auto format case (#350)

---

src/models/chart-model/__tests__/format-pattern-from-range.spec.js
src/models/chart-model/__tests__/index.spec.js
src/models/chart-model/format-pattern-from-range.js
src/models/chart-model/index.js
src/models/tick-model/__tests__/index.spec.js
src/models/tick-model/index.js

Cherry pick from this PR by Quan: https://github.com/qlik-oss/sn-scatter-plot/pull/350
To patch this bug: https://jira.qlikdev.com/browse/QB-16714
File changes are identical to https://github.com/qlik-oss/sn-scatter-plot/pull/350, except for the png file, which did not exist in v3.7.0

fix: axis tick value labels in auto format case

---

src/ext/property-definition/index.js
src/ext/property-definition/styling-panel-definition.js

This PR enables the new styling panel (SENSECLIENT_IM_2206_STYLINGPANEL_SCATTERPLOT) with background options (SENSECLIENT_IM_323_BACKGROUND_OPTIONS) in scatter plot

feat: enabled new styling panel

---

src/hooks/use-models.js
src/services/layout-service/__tests__/meta.spec.js
src/services/layout-service/meta.js

Corrects property name `qUnsupportedFeatures` and updates the use of it slightly. Gets rid of some BDI checks as well, which are not relevant any longer.

fix(QB-17405): pick up and apply DQ limitations

---

src/constants/paths.js
src/models/chart-model/__tests__/animations-properties-handler.spec.js
src/models/chart-model/__tests__/index.spec.js
src/models/chart-model/animations-properties-handler.js
src/models/chart-model/index.js

Animations should only happen when data change, i.e. when users interact with components inside the chart.
Animations should be skipped when users change properties in Advanced Edit Mode, Simple Edit Mode, or Exploration Menu (soft properties).
Before this PR, to skip animations when properties change:
- For Advanced Edit Mode, `constraints.active` was used. This is not ideal, since `constraints.active` being true does not necessarily mean the sheet is in Advanced Edit Mode.
- For Simple Edit Mode and Exploration Menu, individual properties' values were cached and compared with the current values to see if they have changed. This is very tedious.
This PR proposes a better way ([src/models/chart-model/animations-properties-handler.js](https://github.com/qlik-oss/sn-scatter-plot/pull/377/fil …

fix: disable animations when properties change

---

src/constants/paths.js

Fix PR https://github.com/qlik-oss/sn-scatter-plot/pull/378
For some reason, I did not push the change in the path of trendlines to https://github.com/qlik-oss/sn-scatter-plot/pull/378
Similar to videos in https://github.com/qlik-oss/sn-scatter-plot/pull/378

fix: add qTrendLines to data path

---

src/ext/property-definition/styling-definitions/styling-panel-definition.js
src/models/style-model/__tests__/index.spec.js
src/models/style-model/index.js

Reference line label styling will be part of a different JIRA ticket so I will remove it for now.

refactor: remove reference line label styling

---

src/ext/property-definition/styling-definitions/styling-panel-definition.js

Fixed a bug that resulted in an empty chart tab in the styling panel when flag CLIENT_IM_3050 was turned off.
Verification:

fix: remove empty styling chart tab when flag is off

---

package.json
renovate.json

For use in sense-client that only has node 18.15.0 because of https://github.com/nodejs/node/issues/47563

chore: downgrade node version required

---

src/ext/property-definition/styling-definitions/styling-panel-definition.js
src/hooks/use-models.js
src/models/style-model/__tests__/index.spec.js
src/models/style-model/index.js
src/qae/object-definition.js
src/services/color-service/index.js
src/services/color-service/legend/__tests__/index.spec.js
src/services/color-service/legend/index.js

Adding the possibility of configure styling for the following properties for the scatter plot legend
- Legend title
- Legend labels
Flag is CLIENT_IM_3051
Properties added to the components array:
```
{
"key": "legend",
"legend": {
"title": {
"fontFamily": "Courier, monospace",
"fontSize": "24px",
"color": { "index": -1, "color": "#ff5300" }
},
"label": {
"fontFamily": "Didot, serif",
"fontSize": "24px",
"color": { "index": -1, "color": "#00ff0e" }
}
}
}
```

feat: add legend styling to scatter plot

---

package.json
yarn.lock

Bumping qlik-chart-modules to latest version to get fontFamily property on chart specific fonts:

chore: bumping-qlik-chart-modules

---

src/locale/__tests__/index.spec.js
src/locale/index.js

Use a translation key that is unique to the scatterplot to determine wether translations has been loaded or not.
It could happen, if used in the same context as another chart that had the same translation key among it's translations, that the translations for the scatter-plot were never loaded. This should solve that problem.

fix: problem with translations loading

---

nebula.config.js
src/data-handler/__tests__/data-fetcher.spec.js
src/data-handler/data-fetcher.js
src/ext/explore-definition/index.js
src/ext/property-definition/index.js
src/picasso-definition/brush/__tests__/point-brush.spec.js
src/picasso-definition/brush/point-brush.js
src/picasso-definition/components/mini-chart/__tests__/background-window.spec.js
src/picasso-definition/components/mini-chart/__tests__/mini-points.spec.js
src/picasso-definition/components/mini-chart/__tests__/navigation-window.spec.js
src/picasso-definition/components/point-labels/index.js
src/picasso-definition/components/point/__tests__/index.spec.js
src/picasso-definition/components/point/index.js
src/picasso-definition/interactions/is-zoom-by-image.js
src/qae/__tests__/object-definition.spec.js
src/qae/object-definition.js
src/services/layout-service/__tests__/meta.spec.js
src/services/layout-service/meta.js
src/utils/__tests__/is-progressive-allowed.spec.js
src/utils/is-progressive-allowed.js

Makes sure maxVisibleBubbles works properly even when the chart is rendered outside the sense-client.
Includes property in Api spec.
Adds maxVisibleBubbles: 2500 in initialProperties for newly created objects.
Removes the checks for the feature flag `NUM_BUBBLES` which is enabled everywhere anyway.
Also removes the checks for the `PROGRESSIVE_RENDERING` flag which has also been enabled everywhere for a while.
Info: max visible bubbles is 50000
Relates to #429

refactor: add default value for maxVisibleBubbles
